apiVersion: tf.galleybytes.com/v1beta1
kind: Terraform
metadata: # kpt-merge: tf-system/day0-infra
  name: day0-infra
  namespace: tf-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'tf.galleybytes.com|Terraform|tf-system|day0-infra'
spec:
  terraformVersion: 1.5.5
  writeOutputsToStatus: true
  outputsSecret: day0-infra-outputs
  credentials:
  - aws:
      irsa: arn:aws:iam::ACCOUNT_ID:role/mgmt-argocd-terraform-runner
  terraformModule:
    source: https://github.com/infinitydon/eks-infra-terraform.git//tgw-vpc-subnet-nat-terraform?ref=main
  backend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "day0-infra"
        in_cluster_config  = true
        namespace = "tf-system"
      }
    }
  ignoreDelete: false
  keepLatestPodsOnly: true
  taskOptions:
  - for:
    - '*' # The following config affects all task pods
    envFrom:
    - secretRef:
        name: github-pat-credentials # kpt-set: ${github-pat-secret-name}
    env:
    - name: TF_VAR_github_org
      value: crosscom # kpt-set: ${github-org}
    - name: TF_VAR_workload_cluster_region
      value: us-west-2 # kpt-set: ${workload-cluster-region}
    - name: TF_VAR_attach_2nd_eni_lambda_s3_bucket
      value: crosscom-nephio-pdx # kpt-set: ${multus-lambda-s3-bucket}
    - name: TF_VAR_github_repositories
      value: '["argo-telco-ran-5g", "argo-telco-control-plane-5g", "argo-telco-user-plane-5g"]' # kpt-set: ${github-repos}
